lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 999999999999999999
    user_identity_field : email
    encoder:
        signature_algorithm: HS256

    token_extractors:
            # check token in a cookie
            cookie:
                enabled: true
                name:    BEARER